---
src_vocab: 'prepare_data/good_train_clean.src.voc'
dst_vocab: 'prepare_data/good_train_clean.dst.voc'
src_vocab_size: 30000
dst_vocab_size: 30000
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
train:
    devices: '1'
    src_path: 'prepare_data/good_train_clean.src.10000'
    dst_path: 'prepare_data/good_train_clean.dst.10000'
    out_path: 'prepare_data/good_train_clean.out.10000'
    dev_src_path: 'prepare_data/test.8turkers.clean.src'
    dev_dst_path: 'prepare_data/test.8turkers.clean.dst'
    dev_out_path: 'prepare_data/test.8turkers.clean.out'
    tokens_per_batch: 3000
    max_length: 60
    num_epochs: 1
    logdir: 'log/'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5.0
    optimizer: 'adam_decay'
    learning_rate: 0.00005
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 64
    shared_embedding: False
    modelFile: 'save_model1_3000tok/gan/model_epoch_13_step_13000'
